# Check graphic driver (= nvidia-smi)
# Check cuda toolkit (= nvcc --version)
# FROM nvidia/cuda:12.2.0-base-ubuntu20.04
FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        git \
        python3-pip \
        python3-dev \
        python3-opencv \
        libglib2.0-0

# Set the working directory
WORKDIR /usr/work/kafka

# Install any python packages you need
COPY requirements.txt requirements.txt

RUN python3 -m pip install -r requirements.txt

# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Install PyTorch and torchvision
RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu121